version: '3.3'

services:
  data:
    container_name: data
    build:
      context: ./packages/data
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    env_file: 
      - .env
